apiVersion: v1
kind: Service
metadata:
  name: k8s-app-green
  namespace: blue-green-demo
  labels:
    app: k8s-app
    version: green
spec:
  selector:
    app: k8s-app
    version: green
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
